### ISSUE TITLE
Final todo Graph

### ISSUE THREAD

**Issue by FloChehab** [FloChehab/Game-of-news#25]
- [ ] Slightly gradient background
- [ ] Change font (to discuss)
- [ ] (bonus) Make it more appealing

First view:
- [ ] Slight bezier edges
- [ ] Highlight the nodes that are connected to a one that is hovered
- [ ] (bonus) highlight the two nodes that are connected to a hovered edge
- [ ] Tooltips on nodes:
  - [ ] Number of events shared 
  - [ ] Number of common outlets
  - [ ] (bonus) Average tone on all events (update backend)
- [ ] size of the node (keep it as it is now)

  
Second view:
- [ ] Fix layout
- [ ] Names of the source on nodes
- Edge summary (in second view):
  - [ ] (small bonus) Panel with information :
    - [ ] Number of events in common
    - [ ] Average tone distance across shared events
    - [ ] Percentage of agreement
- [ ] (bonus) Tooltips on events with url to go to the articles (need to change the backend)
