### ISSUE TITLE
Final todo : Dashboard

### ISSUE THREAD

**Issue by FloChehab** [FloChehab/Game-of-news#26]
- [x] Side by side for very big screen
- [x] Remove set initial dataset
- [x] Todo better handling of datasets names
- [x] Filtering actor (backend)
- [ ] (bonus) filtering actor frontend
- [x] Move the sliders of the grpah.
- [x] Freeze time window selector when sending request

**Comment by FloChehab** [comment]
@konkou  @striantafyllouEPFL 
The filtering is actually better achieved when using some regexp on the URL

**Comment by FloChehab** [comment]
I won't provide the ability to filter in the frontend, it will be for advance users only.
