### ISSUE TITLE
Final todo : Streamgraph :-P

### ISSUE THREAD

**Issue by FloChehab** [FloChehab/Game-of-news#28]
- [x] fix bugs (transition)

Both views:
- [x] Vertical line on hover
- [x] Hover: show the corresponding number

Main view:
- [x] Change colors (first view)
- [x] Legend, same color as steams, highlights on hover

Second view:
- [x] ~~Slight gradient (at least in second view)~~
- [ ] (bonus) information panel on the source
